application: warning-track
version: 2-1-0
runtime: go
api_version: go1
automatic_scaling:
  max_idle_instances: 3
  min_pending_latency: 100ms

handlers:
- url: /
  script: _go_app

- url: /deleteGamesStatuses
  script: _go_app
  login: admin

- url: /games
  script: _go_app

- url: /fetchGames
  script: _go_app
  login: admin

- url: /fetchStatuses
  script: _go_app
  login: admin

- url: /fetchAllStatuses
  script: _go_app
  login: admin

- url: /setTwitterCredentials
  script: _go_app
  login: admin

- url: /tv
  script: _go_app

- url: /*
  application_readable: true
  static_dir: static
