application: warning-track
version: 1-1-1
runtime: go
api_version: go1

handlers:
- url: /
  script: _go_app

- url: /games
  script: _go_app

- url: /fetchGames
  script: _go_app
  login: admin

- url: /fetchStatuses
  script: _go_app
  login: admin

- url: /fetchAllStatuses
  script: _go_app
  login: admin

- url: /setTwitterCredentials
  script: _go_app
  login: admin

- url: /deleteGamesStatuses
  script: _go_app
  login: admin

- url: /*
  application_readable: true
  static_dir: static
