runtime: go111
automatic_scaling:
  min_pending_latency: 100ms

handlers:
- url: /
  script: auto

- url: /deleteGamesStatuses
  script: auto
  login: admin

- url: /faq
  script: auto

- url: /games
  script: auto

- url: /fetchGames
  script: auto
  login: admin

- url: /fetchStatuses
  script: auto
  login: admin

- url: /fetchAllStatuses
  script: auto
  login: admin

- url: /setTwitterCredentials
  script: auto
  login: admin

- url: /tv
  script: auto

- url: /*
  static_dir: www
